---
version: "{build}"
platform:
- x86
- x64
clone_depth: 50
cache:
- C:\tools\mingw32
- C:\tools\mingw64
environment:
  GIT_NAME:
    secure: JatNbOZZZKMvMHL8sRq9XpHgESzJ13eh9NHbMK99rX8=
  GIT_EMAIL:
    secure: 7EAYZJ5nFqEhMKcPmUvnqPp81XAoJEILzDJJ2qZXrKA=
  GH_TOKEN:
    secure: xx7og+aLQbdBSsdVo79OTGtdfqedOpYpIJjduNlzjFSXsTkD8NX8fEPq0XE1KT5n
  SF_KEY:
    secure: 6Vuo+sNP2YT/iI4ilNDdyJbKpu1AYxSpkdwjJxeZ3BVXM0XQQnG7VS/6IspV9kgWXmYpeVnUTqpoxAg7GDf3MTN9SeXgwHuSsblIAHDaOJk=
  SF_API:
    secure: gEDrho4yNr5++SbgkWsxQiFA62GJfTLrZU9Dzjz9HCUcS7XwjTGg3XsFm84w6B1s
  build_tree: mingw-Build
  config: Release
  URHO3D_D3D11: 1
  MINGW: 1
  x86_64-posix-seh: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/6.3.0/threads-posix/seh/x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z
  i686-posix-dwarf: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-posix/dwarf/i686-6.3.0-release-posix-dwarf-rt_v5-rev1.7z
  matrix:
  - URHO3D_LIB_TYPE: STATIC
  - URHO3D_LIB_TYPE: SHARED
before_build:
- rake ci_timer
- set "APPVEYOR_REPO_COMMIT=%APPVEYOR_REPO_COMMIT%~"
- ps: $env:COMMIT_MESSAGE = $(git log --format=%B -n 1 $env:APPVEYOR_REPO_COMMIT);
    if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:RELEASE_TAG = $env:APPVEYOR_REPO_TAG_NAME
    }; if ($env:RELEASE_TAG -or ($env:APPVEYOR_REPO_BRANCH -notmatch "[^-]+-[^-]+-CI"
    -and (select-string '\[ci package\]' -inputobject $env:COMMIT_MESSAGE))) { $env:PACKAGE_UPLOAD
    = "1"; do { "Installing doxygen and graphviz..."; choco install doxygen.install
    graphviz >$null } until ($?); } else { $env:URHO3D_TOOLS = "0"; iex ((new-object
    net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-desktop.ps1'))
    }
- if "%PLATFORM%" == "x64" (set "URHO3D_64BIT=1" && set "MINGW_URL=%x86_64-posix-seh%"
  && set "ARCH=64") else (set "MINGW_URL=%i686-posix-dwarf%" && set "ARCH=32")
- if not exist "C:\tools\mingw%ARCH%" curl -fsSL -o "mingw.7z" -O "%MINGW_URL%" &&
  7z x -y -o"C:\tools" "mingw.7z" >nul && echo "Installed MinGW compiler toolchain
  to C:\tools"
- set "PATH=C:\tools\mingw%ARCH%\bin;%PATH%"
build_script:
- rake ci && if "%PACKAGE_UPLOAD%" == "1" (rake ci_package_upload && move %build_tree%\*.zip
  . && rd /S /Q %build_tree%\_CPack_Packages)
- rake ci_timer
after_build:
- if "%PLATFORM%:%URHO3D_LIB_TYPE%" == "x64:SHARED" rake ci_delete_mirror
test: false
artifacts:
- path: ".\\*.zip"
deploy: false
